-- liquibase formatted sql

-- changeset hoahtm:1765902278757-1
CREATE TABLE app_user
(
    id         UUID                  NOT NULL,
    username   VARCHAR(50)           NOT NULL,
    email      VARCHAR(100)          NOT NULL,
    password   VARCHAR(255),
    is_enabled BOOLEAN DEFAULT TRUE  NOT NULL,
    is_locked  BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-2
CREATE TABLE oauth2_client
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id                 VARCHAR(100)                            NOT NULL,
    client_secret             VARCHAR(255),
    client_name               VARCHAR(100),
    authentication_methods    TEXT,
    authorization_grant_types TEXT,
    redirect_uris             TEXT,
    scopes                    TEXT,
    access_token_ttl          INTEGER,
    refresh_token_ttl         INTEGER,
    created_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth2_client PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-3
CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     UUID                                    NOT NULL,
    session_id  UUID,
    token       VARCHAR(255)                            NOT NULL,
    chain_id    VARCHAR(255)                            NOT NULL,
    issued_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiry_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked     BOOLEAN DEFAULT FALSE                   NOT NULL,
    replaced_by VARCHAR(255),
    ip_address  VARCHAR(45),
    user_agent  TEXT,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-4
CREATE TABLE revoked_token
(
    jti               VARCHAR(255) NOT NULL,
    user_id           UUID,
    chain_id          VARCHAR(255) NOT NULL,
    revoked_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiry_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revocation_reason VARCHAR(50),
    CONSTRAINT pk_revoked_token PRIMARY KEY (jti)
);

-- changeset hoahtm:1765902278757-5
CREATE TABLE user_external_account
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          UUID                                    NOT NULL,
    provider         VARCHAR(50)                             NOT NULL,
    provider_user_id VARCHAR(255)                            NOT NULL,
    provider_email   VARCHAR(100),
    access_token     TEXT,
    refresh_token    TEXT,
    token_expiry     TIMESTAMP WITHOUT TIME ZONE,
    scopes           TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_external_account PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-6
CREATE TABLE user_role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-7
CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

-- changeset hoahtm:1765902278757-8
CREATE TABLE user_session
(
    id          UUID                  NOT NULL,
    user_id     UUID                  NOT NULL,
    device_info TEXT,
    ip_address  VARCHAR(45),
    user_agent  TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_active TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked     BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_user_session PRIMARY KEY (id)
);

-- changeset hoahtm:1765902278757-9
ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

-- changeset hoahtm:1765902278757-10
ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

-- changeset hoahtm:1765902278757-11
ALTER TABLE oauth2_client
    ADD CONSTRAINT uc_oauth2_client_client UNIQUE (client_id);

-- changeset hoahtm:1765902278757-12
ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

-- changeset hoahtm:1765902278757-13
ALTER TABLE user_role
    ADD CONSTRAINT uc_user_role_name UNIQUE (name);

-- changeset hoahtm:1765902278757-14
ALTER TABLE user_external_account
    ADD CONSTRAINT uk_provider_user UNIQUE (provider, provider_user_id);

-- changeset hoahtm:1765902278757-15
ALTER TABLE user_external_account
    ADD CONSTRAINT uk_user_provider UNIQUE (user_id, provider);

-- changeset hoahtm:1765902278757-16
CREATE INDEX idx_external_provider ON user_external_account (provider);

-- changeset hoahtm:1765902278757-18
CREATE INDEX idx_oauth2_client_id ON oauth2_client (client_id);

-- changeset hoahtm:1765902278757-19
CREATE INDEX idx_refresh_token_chain ON refresh_token (chain_id);

-- changeset hoahtm:1765902278757-20
CREATE INDEX idx_refresh_token_token ON refresh_token (token);

-- changeset hoahtm:1765902278757-22
CREATE INDEX idx_revoked_chain ON revoked_token (chain_id);

-- changeset hoahtm:1765902278757-23
CREATE INDEX idx_revoked_expiry ON revoked_token (expiry_at);

-- changeset hoahtm:1765902278757-25
CREATE INDEX idx_session_active ON user_session (last_active);

-- changeset hoahtm:1765902278757-27
CREATE INDEX idx_user_email ON app_user (email);

-- changeset hoahtm:1765902278757-28
CREATE INDEX idx_user_username ON app_user (username);

-- changeset hoahtm:1765902278757-29
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_SESSION FOREIGN KEY (session_id) REFERENCES user_session (id) ON DELETE SET NULL;

-- changeset hoahtm:1765902278757-30
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);

-- changeset hoahtm:1765902278757-31
ALTER TABLE revoked_token
    ADD CONSTRAINT FK_REVOKED_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
CREATE INDEX idx_revoked_user ON revoked_token (user_id);

-- changeset hoahtm:1765902278757-32
ALTER TABLE user_external_account
    ADD CONSTRAINT FK_USER_EXTERNAL_ACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
CREATE INDEX idx_external_user ON user_external_account (user_id);

-- changeset hoahtm:1765902278757-33
ALTER TABLE user_session
    ADD CONSTRAINT FK_USER_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE;
CREATE INDEX idx_session_user ON user_session (user_id);

-- changeset hoahtm:1765902278757-34
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (id);

-- changeset hoahtm:1765902278757-35
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_role FOREIGN KEY (role_id) REFERENCES user_role (id);


-- changeset hoahtm:1765902278757-36
-- Insert default roles
INSERT INTO user_role (name) VALUES ('USER') ON CONFLICT (name) DO NOTHING;
INSERT INTO user_role (name) VALUES ('ADMIN') ON CONFLICT (name) DO NOTHING;

-- changeset hoahtm:1765902278757-37
-- Insert test user (password: 'password' encoded with BCrypt)
INSERT INTO app_user (id, username, email, password, is_enabled, is_locked, created_at) 
VALUES (
    gen_random_uuid(), 
    'testuser', 
    'test@example.com', 
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqyc6YxlkjE8n.jEsOZqDAa', -- password: 'password'
    true, 
    false, 
    CURRENT_TIMESTAMP
) ON CONFLICT (username) DO NOTHING;

-- changeset hoahtm:1765902278757-38
-- Assign USER role to test user
INSERT INTO user_roles (role_id, user_id) 
SELECT ur.id, au.id 
FROM user_role ur, app_user au 
WHERE ur.name = 'USER' AND au.username = 'testuser'
ON CONFLICT DO NOTHING;